config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end 
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts
    resources :post_comments, only: [:destroy] 
  end
  
  scope module: :public do
    devise_for :users
  
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    
    root to: "homes#top"
    
    get 'user/mypage' => 'users#mypage',as: :'mypage'
    resources :users do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    
    get 'search', to: 'searches#search'
  end 

  resources :notifications, only: [:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :notification, as: :notifiable, dependent: :destroy
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end    
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("body LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("body LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  
  def index
    @user = current_user
    @posts = Post.page(params[:page]).order("created_at DESC")
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
<h1>つぶやき一覧</h1>
<table class="table table-hober table-inverse">
  <thead>
    <tr>
      <th>Title</th>
      <th>つぶやき</th>
      <th>ユーザー名</th>
      <th>コメント数</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, admin_post_path(post.id) %></td>
          <td><%= post.body %></td>
          <td><%= link_to post.user.name, admin_user_path(post.user.id) %></td>
          <td><%= "#{post.post_comments.count} 件" %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts %>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>ユーザー情報</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>ユーザー名</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>プロフィール</th>
          <th><%= @user.profile %></th>
        </tr>
      
      </table>
    <%= link_to "ユーザー削除", admin_user_path(@user), method: :delete, data: { confirm: 'ユーザーを削除してよろしいですか？' },class:"btn btn-sm btn-danger" %>
    <%= link_to "ユーザー一覧へ", admin_dashboards_path, class:"btn btn-sm btn-primary" %>
    <%= link_to "つぶやき削除", admin_post_path, method: :delete, data: { confirm: 'このつぶやきを削除してよろしいですか？' },class:"btn btn-sm btn-danger" %>
    </div>
    <div class="col-md-8 offset-md-1"> 
      <h2>投稿詳細</h2>
        <% if @error_comment.present? %>
          <p>コメントを記載してください。</p>
          <ul>
            <% @error_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>つぶやき</th>
            <th>ユーザー名</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <tr>
            <td><%= @post.title %></td>
            <td><%= @post.body %></td>
            <td><%= link_to @post.user.name, admin_user_path(@post.user.id) %></td>
          </tr>
        </tbody>
      </table>
      <%= @post.created_at.strftime('%Y/%m/%d') %>
    
      <p>コメント件数：<%= @post.post_comments.count %></p>
      <% @post.post_comments.each do |post_comment| %>
        <div class= "row border-top">
          <div class= "col-md-3">
            <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
            <%= link_to post_comment.user.name, admin_user_path(post_comment.user.id) %>
            <%= post_comment.created_at.strftime('%Y/%m/%d') %>
          </div>
          <div class= "col-md-7">
            <%= post_comment.comment %>
          </div>
          <div class= "col-md-2">
            <%= link_to "削除", admin_post_comment_path(post_comment), method: :delete %>
          </div>
        </div>
      <% end %>
      
      
    </div>
  </div>
</div>