config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end 
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
    resources :posts
    resources :post_comments, only: [:destroy] 
  end
  
  scope module: :public do
    devise_for :users
  
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    
    root to: "homes#top"
    
    get 'user/mypage' => 'users#mypage',as: :'mypage'
    resources :users do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    
    get 'search', to: 'searches#search'
  end 

  resources :notifications, only: [:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy
  
  after_create do
    create_notification(user_id: post.user_id)
  end 
  
  validates :user_id, uniqueness: {scope: :post_id}
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

# #notification = Notification.new(user_id: 7, notifiable_id: 10, notifiable_type: "Relationship")

# if notification.save
#   puts "Notification created successfully"
# else
#   puts "Failed to create notification: #{notification.errors.full_messages.join(", ")}"
# end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :notification, as: :notifiable, dependent: :destroy
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end    
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("body LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("body LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
  validates :title, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy
  
  after_create do
    post = self.post
    Notification.create(
      user_id: post.user_id,
      notifiable_id: id,
      notifiable_type: "PostComment")
  end  
  
  validates :comment, presence: true
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  has_one :notification, as: :notifiable, dependent: :destroy
  
  after_create do
    Notification.create!(
      user_id: followed_id,
      notifiable_id: id,
      notifiable_type: "Relationship")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  
    has_many :posts, dependent: :destroy
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :followings, through: :relationships, source: :followed
    has_many :followers, through: :reverse_of_relationships, source: :follower
    has_many :notifications, dependent: :destroy
    has_one_attached :profile_image
    
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
    
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end 
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end 
  
  def following?(user)
    followings.include?(user)
  end 
    
    
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :profile, length: {maximum: 60 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  before_action :authenticate_user!, except: [:top], unless: :admin_controller?
  
  private
  
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    end
  end
 
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
 
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
  

  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def update
    notification = current_user.notifications.find(params[:id])
    notification.update(read: true)
    
    case notification.notifiable_type
    when "Post"
      redirect_to post_path(notification.notifiable)
    when "PostComment"
      redirect_to post_path(notification.notifiable.post)
    when "Relationship"
      redirect_to user_path(notification.notifiable.follower_id)
    else
      redirect_to user_path(notification.notifiable.user)
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_message(notification)
    case notification.notifiable_type
    when "Post"
      "フォローしている#{notification.notifiable.user.name}さんが#{notification.notifiable.title}を投稿しました"
    when "Favorite"
      "投稿した#{notification.notifiable.post.title}が#{notification.notifiable.user.name}さんにいいねされました"
    when "PostComment"
      "投稿した#{notification.notifiable.post.title}が#{notification.notifiable.user.name}さんにコメントされました"
    else
      user = User.find(notification.notifiable.follower_id)
      "#{user.name}さんにフォローされました"
    end
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">ママやき 管理者用ページ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" 
                        aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ユーザー一覧', admin_dashboards_path %>
      <%= link_to 'つぶやき一覧', admin_posts_path %>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>   
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ママやき</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <script src="https://kit.fontawesome.com/1ee55760e3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">ママやき</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" 
                          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to root_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-house"></i> トップ
                <% end %>
              </li>
              <li>
                <%= link_to mypage_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-user"></i> マイページ
                <% end %>
              </li>
              <li>
                <%= link_to posts_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-list"></i>投稿一覧
                <% end %>
              </li>
              <li>
                <%= link_to new_post_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-comment"></i> 新規投稿
                <% end %>
              </li>
              <li class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Notification
                  <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% if current_user.notifications.where(read: false).any? %>
                    <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                    <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                      <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                    <% end %>
                  <% else %>
                    <span class="dropdown-item disabled">未読の通知はありません</span>
                  <% end %>
                </div>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-house"></i> トップ
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-right-to-bracket"></i> ログイン
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-dark" do %>
                  <i class="fa-solid fa-user-plus"></i> 新規登録
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>    
    <% if user_signed_in? %>
  <div class="search_form text-right">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['ユーザー'], ['つぶやき']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
    <%= yield %>
  </body>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>